import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "prod_01J8F",
    slug: "body-lotion-a",
    name: "Body Lotion A",
    description: "Infused with African botanicals and cold-pressed marula oil. Deeply replenishes moisture barriers while soothing sensitive skin. Fast-absorbing, velvet finish.",
    basePrice: 200,
    images: ["/images/body-lotion-a.jpg"],
    status: "ACTIVE",
    category: "Body Care",
    badge: "BEST SELLER",
    concerns: ["Deep Hydration", "Soothing & Sensitive"],
    ingredients: ["Cold-Pressed Marula"],
    rating: 5,
    reviewCount: 48,
    stock: 100,
    trackInventory: false,
    sortOrder: 0,
  },
  {
    id: "prod_02J8F",
    slug: "body-lotion-b",
    name: "Body Lotion B",
    description: "Formulated with nourishing neroli, frankincense, and calming chamomile extract. Restores elasticity and revitalizes natural tone throughout the day. Ultra-hydrating and gentle.",
    basePrice: 45,
    images: ["/images/body-lotion-b.jpg"],
    status: "ACTIVE",
    category: "Body Care",
    badge: "AWARD WINNER",
    concerns: ["Barrier Repair", "Soothing & Sensitive"],
    ingredients: ["Neroli & Frankincense", "Cape Chamomile"],
    rating: 5,
    reviewCount: 16,
    stock: 100,
    trackInventory: false,
    sortOrder: 0,
  },
  {
    id: "prod_03J8F",
    slug: "radiance-face-oil",
    name: "Radiance Face Oil",
    description: "A potent blend of rosehip, squalane, and vitamin C. Delivers an instant, luminous glow while locking in deep moisture. Lightweight and non-comedogenic.",
    basePrice: 320,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800"],
    status: "ACTIVE",
    category: "Face Care",
    badge: "NEW HARVEST",
    concerns: ["Glow & Radiance", "Deep Hydration"],
    ingredients: ["Cold-Pressed Marula"],
    rating: 4.8,
    reviewCount: 112,
    stock: 100,
    trackInventory: false,
    sortOrder: 0,
  },
  {
    id: "prod_04J8F",
    slug: "clarifying-cleanser",
    name: "Clarifying Cleanser",
    description: "Gentle daily gel cleanser infused with salicylic acid and aloe vera. Sweeps away impurities without stripping the skin's natural barrier.",
    basePrice: 180,
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800"],
    status: "ACTIVE",
    category: "Face Care",
    concerns: ["Barrier Repair", "Soothing & Sensitive"],
    ingredients: ["Wild Baobab Oil"],
    rating: 4.5,
    reviewCount: 89,
    stock: 100,
    trackInventory: false,
    sortOrder: 0,
  },
  {
    id: "prod_05J8F",
    slug: "night-repair-serum",
    name: "Night Repair Serum",
    description: "Overnight recovery treatment featuring bakuchiol and peptides. Accelerates cellular renewal for visibly firmer, smoother skin by morning.",
    basePrice: 450,
    images: ["https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800"],
    status: "ACTIVE",
    category: "Oils & Serums",
    concerns: ["Deep Hydration", "Barrier Repair"],
    ingredients: ["Cape Chamomile"],
    rating: 4.9,
    reviewCount: 205,
    stock: 100,
    trackInventory: false,
    sortOrder: 0,
  },
  {
    id: "prod_06J8F",
    slug: "botanical-bundle",
    name: "The Botanical Routine",
    description: "Our signature three-step system: Clarifying Cleanser, Radiance Face Oil, and Night Repair Serum. The ultimate gift of glowing skin.",
    basePrice: 850,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800"],
    status: "ACTIVE",
    category: "Bundles",
    concerns: ["Glow & Radiance", "Barrier Repair"],
    ingredients: ["Cold-Pressed Marula", "Wild Baobab Oil", "Neroli & Frankincense"],
    rating: 5,
    reviewCount: 34,
    stock: 100,
    trackInventory: false,
    sortOrder: 0,
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug);
}
